/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { jwks_cert__T } from './jwks_cert__b.js'
import type { jwks_x5c__T } from './jwks_x5c__b.js'
import type { jwt_token_decoded__T } from './jwt_token_decoded__b.js'
import type { koa_jwt_token_decoded__T } from './koa_jwt_token_decoded__b.js'
import type { verify_jwt_email__T } from './verify_jwt_email__b.js'
import type { verify_jwt_user_id__T } from './verify_jwt_user_id__b.js'
export interface auth0_service_ctx_I {
	jwks_cert_?:jwks_cert__T
	jwks_x5c_?:jwks_x5c__T
	jwt_token_decoded_?:jwt_token_decoded__T
	koa_jwt_token_decoded_?:koa_jwt_token_decoded__T
	verify_jwt_email_?:verify_jwt_email__T
	verify_jwt_user_id_?:verify_jwt_user_id__T
}